# Use the Docker socket from the extension backend:
# https://docs.docker.com/desktop/extensions-sdk/guides/use-docker-socket-from-backend/
services:
  myExtension:
    image: ${DESKTOP_PLUGIN_IMAGE}
    container_name: dockerpulse
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock
      # Create a named volume which is mapped to the /grafana folder in the extension container
      # (The /grafana folder is added to the extension container in the extension's Dockerfile)
      - shared-grafana-configs:/grafana:ro
      # Create a named volume which is mapped to the /prometheus folder in the extension container
      # (The /prometheus folder is added to the extension container in the extension's Dockerfile)
      - shared-prometheus-configs:/prometheus:ro
    depends_on:
      - grafana
    ports:
      # Expose port 3333 to the host so that you can see metrics on localhost:3333/metrics
      - 3333:3333

  prometheus:
    # Pulling a custom image that has been pushed to the hub that has been configured to scrape
    # from cadvisor so there is no need to create a bind mount that configures the prometheus.yml file
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      # Create a named volume for the prometheus data
      - prometheusdata:/prometheus
      # Share the named volume with the prometheus container
      - shared-prometheus-configs:/etc/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 2999:3000
    volumes:
      # Share the named volume with the grafana container
      - shared-grafana-configs:/etc/grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    depends_on:
      - prometheus

volumes:
  prometheusdata:
  shared-grafana-configs:
  shared-prometheus-configs:
