# Configuration file for Prometheus
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/

scrape_configs:
  - job_name: docker_container_metrics
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:3333']
