# Configuration file for Prometheus
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/

scrape_configs:
  - job_name: docker_container_metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['docker.host.internal:3333']
